
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=automium/reactor

matrix:
  include:
  - name: "latest"
    env: TAG=latest
  - name: "basic"
    env: TAG=basic
  - name: "acl"
    env: TAG=acl
  - name: "encrypt"
    env: TAG=encrypt
  - name: "encrypt-basic"
    env: TAG=encrypt-basic

script:
  - docker build -f Dockerfile.${TAG} --no-cache --pull --tag "${IMAGE_NAME}:example-${TAG}" .

before_deploy:
  - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASS}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:example-${TAG}"
  on:
    branch: master